name: Build QuestNav App
on:
  workflow_call:
    inputs:
      versionYear:
        description: 'Current FRC Year'
        required: true
        default: 2025
        type: number
      versionMajor:
        description: 'Major version'
        required: true
        default: 1
        type: number
      versionMinor:
        description: 'Minor version'
        required: true
        default: 0
        type: number
      versionPatch:
        description: 'Patch version'
        required: true
        default: 0
        type: number
      versionType:
        description: 'Type of version'
        required: false
        type: string
    secrets:
      UNITY_LICENSE:
        description: 'Unity License'
        required: true
      UNITY_EMAIL:
        description: 'Unity Email'
        required: true
      UNITY_PASSWORD:
        description: 'Unity Password'
        required: true
    outputs:
      apk-artifact-name:
        description: "Name of the uploaded APK artifact"
        value: ${{ jobs.build-unity.outputs.apk-artifact-name }}
      apk-filename:
        description: "Filename of the built APK"
        value: ${{ jobs.build-unity.outputs.apk-filename }}

jobs:
  build-unity:
    runs-on: ubuntu-latest
    outputs:
      apk-artifact-name: ${{ steps.upload.outputs.artifact-id }}
      apk-filename: ${{ steps.buildUnity.outputs.buildVersion }}.apk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: unity
          sparse-checkout-cone-mode: false
          lfs: true

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: false
          dotnet: false

      - name: Setup Caching
        uses: actions/cache@v3
        with:
          path: unity/Library
          key: Library-QuestNav-Android
          restore-keys: |
            Library-
            Library-Questnav-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install NuGetForUnity
        run: dotnet tool install --global NuGetForUnity.Cli

      - name: Restore NuGetForUnity Packages
        run: nugetforunity restore unity/

      - name: Calculate Android Version Code
        id: version-code
        run: |
          VERSION_CODE=$(( (${{ inputs.versionYear }} - 2020) * 100000000 + ${{ inputs.versionMajor }} * 1000000 + ${{ inputs.versionMinor }} * 1000 + ${{ inputs.versionPatch }} ))
          echo "code=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Build Unity Project for Android
        uses: game-ci/unity-builder@v4
        id: buildUnity
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: unity
          targetPlatform: Android
          customParameters: -developmentBuild
          versioning: Custom
          version: ${{ inputs.versionYear }}.${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}${{ inputs.versionType && format('-{0}', inputs.versionType) || '' }}
          androidVersionCode: ${{ steps.version-code.outputs.code }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: questnav-apk-${{ inputs.versionYear }}-${{ inputs.versionMajor }}.${{ inputs.versionMinor }}.${{ inputs.versionPatch }}${{ inputs.versionType && format('-{0}', inputs.versionType) || '' }}
          path: build/Android/*.apk
          retention-days: 7